name: Deploy Docker Stack to Scaleway

on:
  push:
    paths:
      - 'docker-compose/**'
      - 'config/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Scaleway
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Scaleway CLI
      run: |
        curl -sL https://github.com/scaleway/scaleway-cli/releases/latest/download/scaleway-cli_$(uname -s)_$(uname -m).tar.gz | tar xz -C /usr/local/bin
        scw -v

    - name: Login to Scaleway
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      run: scw init non-interactive --access-key "$SCW_ACCESS_KEY" --secret-key "$SCW_SECRET_KEY" --region fr-par

    - name: Deploy Docker Stack
      run: |
        docker-compose -f docker-compose/docker-compose.yml up -d --build
